# Generated by Django 3.2.25 on 2025-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerstore',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
