# Generated by Django 4.2 on 2025-02-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_sellerstore_instagram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=50, unique=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='scraper/covers/')),
                ('images', models.JSONField()),
                ('video', models.FileField(blank=True, null=True, upload_to='scraper/reels/')),
                ('is_reel', models.BooleanField(default=False)),
                ('is_ai_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_posts', to='sellers.sellerstore')),
            ],
        ),
    ]
