# Generated by Django 4.2 on 2025-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpost',
            name='is_ai_read',
        ),
        migrations.AlterField(
            model_name='scrapedpost',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedpost',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scrapedpost',
            name='post_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scrapedpost',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
