# Generated by Django 4.2 on 2025-02-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_scrapedpost_is_ai_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpost',
            name='is_ai_read',
            field=models.BooleanField(default=False),
        ),
    ]
