# Generated by Django 4.2 on 2025-02-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0003_scrapedpost_is_ai_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processed', to='scraper.scrapedpost')),
            ],
        ),
    ]
